### ISSUE TITLE
Disabling submit button

### ISSUE THREAD

**Issue by GalacticGlum** [Availity/availity-reactstrap-validation#105]
I would like to disable the submit button unless the form is valid (that is, all validators have passed).  Or, I would like to have the submit button be disabled whilst the form validates. I tried having an "isLoading" bool in my state and then setting it when the submit button is clicked but that would disable my button leading to no validation. Essentially, I need to disable my submit button after the validation is started but before anything actually is validated.

How do I go about implementing this?

**Comment by TheSharpieOne** [comment]
See #100
