### ISSUE TITLE
Is there a way to use react-input-mask with validating fields?

### ISSUE THREAD

**Issue by lawrenz1337** [Availity/availity-reactstrap-validation#107]
`react-input-mask` uses the same parameter `tag` as `AvField` for CustomInput from reactstrap. They override eachother and default input is rendered istead

**Comment by TheSharpieOne** [comment]
I have a PR up, it should allow you to do something like:
```jsx
  <AvField tag={[CustomInput, ReactInputMask]} ... />
```
to have `AvField` render a `CustomInput` with a `tag` of `ReactInputMask`

**Comment by lawrenz1337** [comment]
@TheSharpieOne Thanks for you work! But it doesn't seem to work yet... You can check my example here https://stackblitz.com/edit/react-dw17ff

**Comment by nicobailon** [comment]
@TheSharpieOne I can also confirm that this does not seem to work. I tweaked @lawrenz1337's example here: https://stackblitz.com/edit/react-dw17ff and I'm seeing:
`Error in /turbo_modules/availity-reactstrap-validation@2.5.0/lib/AvInput.js (85:12)`
`tags is not defined`

**Comment by GoPro16** [comment]
@nicobailon   I am not sure you pasted your version correctly. I am seeing the same code as what @lawrenz1337  pasted.

**Comment by TheSharpieOne** [comment]
the error about `tags` is coming from this lib. There is an unreleased fix: #112. @GoPro16 can you or @robmcguinness cut a new release to include that fix?

**Comment by nicobailon** [comment]
@GoPro16 apologies. I have fixed the link.

**Comment by robmcguinness** [comment]
I'll release shortly

**Comment by GoPro16** [comment]
Just released `@2.5.1`

**Comment by henrique-barreto** [comment]
Can we get a working example of how to use input maks?

**Comment by TheSharpieOne** [comment]
@henrique-barreto check out https://stackblitz.com/edit/react-8smaux?file=Hello.js

```jsx
        <AvForm>
          <AvField
            label="Phone Number"
            type="tel"
            mask="(999) 999-9999"
            maskChar="-"
            name='Test'
            tag={[Input, InputMask]}
            required
            helpMessage="Valid NANP phone number cannot start with a 1"
          />
        </AvForm>
```
