### ISSUE TITLE
errors values onSubmit stated returning array suddenly

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [Availity/availity-reactstrap-validation#108]
i am checking some conditions on the form submit to check if there is an error in form or not.

This is my form 
             <AvForm  className="form-horizontal col-6 col-sm-6" onSubmit={this.handleSubmit} >
                   ----- fields---
                  <Button type='submit' className='btn btn-cn'>Save </Button>
                </AvForm>
and this is the submit handler used in many forms
 handleSubmit(event,errors,values){
    if(errors === null || errors=='undefined' || errors === ''){
-----------------execure the API call--------
}

The issue is the errors param in submit function started returning the empty array for no errors suddenly and now all those pages who have this condition stopped working as empty error is now returning array. Its hectic the change the condition all places so is there any solutions to this ?

**Comment by TheSharpieOne** [comment]
It has always returned an array.

https://github.com/Availity/availity-reactstrap-validation/blame/master/src/AvForm.js#L409
You can see `errors` defaults to an empty array, that `errors` var gets returned in `return` object,
https://github.com/Availity/availity-reactstrap-validation/blame/master/src/AvForm.js#L437

The values are destructed (it says the line was changed 9 months ago, but it didn't change the destructing)
https://github.com/Availity/availity-reactstrap-validation/blame/master/src/AvForm.js#L99

Then finally the user provided callback function is called 
https://github.com/Availity/availity-reactstrap-validation/blame/master/src/AvForm.js#L105

**Comment by AbhaysinghBhosale** [comment]
> It has always returned an array.
> 
> https://github.com/Availity/availity-reactstrap-validation/blame/master/src/AvForm.js#L409
> You can see `errors` defaults to an empty array, that `errors` var gets returned in `return` object,
> https://github.com/Availity/availity-reactstrap-validation/blame/master/src/AvForm.js#L437
> 
> The values are destructed (it says the line was changed 9 months ago, but it didn't change the destructing)
> https://github.com/Availity/availity-reactstrap-validation/blame/master/src/AvForm.js#L99
> 
> Then finally the user provided callback function is called
> https://github.com/Availity/availity-reactstrap-validation/blame/master/src/AvForm.js#L105

I am using the same code from last few months and it was never returning the empty array.Just on Friday its started returning the empty array for no errors

**Comment by GoPro16** [comment]
If you are still experiencing issues, please let us know, otherwise closing since this has always been the default behavior.
