### ISSUE TITLE
Support Typescript

### ISSUE THREAD

**Issue by alexey-gorshkov** [Availity/availity-reactstrap-validation#118]
Please help to connect for the project React(react-app-rewired) + TS.

I use in .tsx file 
`import { AvForm, AvInput } from 'availity-reactstrap-validation';`

My error  

> error TS7016: Could not find a declaration file for module 'availity-reactstrap-validation'. 'D:\git\dxw\upta-ext\node_modules\availity-reactstrap-validation\lib\index.js' implicitly has an 'any' type.

I created file typings/availity-reactstrap-validation/indext.d.ts

```
declare module 'AvForm';
declare module 'AvInput';
```

app/tsconfig.json

```
"compilerOptions": {
...
"typeRoots" : [
      "./node_modules/@types",
      "./typings"
    ]
},
"exclude": [
    "node_modules",
    ...
    "typings"
  ]
```
I do not find a solution. The **@types/availity-reactstrap-validation** package was not found.
How can I solve my problem?

**Comment by alexey-gorshkov** [comment]
My problem was that I didn’t call the module correctly. Right:
`declare module 'availity-reactstrap-validation';`

Now the project is compiled!

The next problem is the required attribute for AvInput
> [tslint] Value must be set for boolean attributes [jsx-boolean-value]

I solve it by disabling this option in tslint.

It will be very cool if you release the library **@types/availity-reactstrap-validation**

**Comment by trinneert** [comment]
this is marked closed, but I've just installed this and am having this same problem

**Comment by alexey-gorshkov** [comment]
**Today I connected this library with Typescript support in a new project.**
This instruction is for beginners:

1) You need to create a typings folder next to your tsconfig.json file

`typings/availity-reactstrap-validation/index.d.ts`

2) In the created file index.d.ts add the contents:

`declare module 'availity-reactstrap-validation';`

3) Make changes to the tsconfig.json file. Add typeRoots block:

```
"compilerOptions": {
      "typeRoots" : [
        "./node_modules/@types",
        "./typings"
      ],
```

4) Restart your editor and you can use this in your tsx file.

`import { AvForm, AvField } from 'availity-reactstrap-validation';`

**I wish you all success! You are already well done!**
