### ISSUE TITLE
React does not recognize the `helpMessage` prop on a DOM element.

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [Availity/availity-reactstrap-validation#121]
Getting this error in the browser console. tried to make is small case  but its not working. Will be better if this props is made smaller case in package.

Following is the error shown console
`arning: React does not recognize the `helpMessage` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `helpmessage` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in input (created by Input)
    in Input (created by AvInput)
    in AvInput (at Update.js:199)
    in div (created by Col............. and so on)`

**Comment by TheSharpieOne** [comment]
`AvField` has `helpMessage`, `AvInput` does not.

**Comment by AbhaysinghBhosale** [comment]
Yes i have added AvField and its working but the reason for using the AvInput is that i want to use icon with field ie there should be eye icon in right end of field to view types password. but using av field i could not use that .

**Comment by TheSharpieOne** [comment]
You'll have to use `AvGroup` with `AvInput` and `AvFeedback` from this library along with `Label` and `FormText` from reactstrap. That is basically what `AvField` does, it's just a convenience component which wraps other components to make it easier for a common use-case.
