### ISSUE TITLE
Swap moment with dayjs

### ISSUE THREAD

**Issue by GoPro16** [Availity/availity-reactstrap-validation#125]
`moment` accounts for over 60% of this packages size.

[moment](https://github.com/moment/moment/): 65.9KB
[dayjs](https://github.com/iamkun/dayjs): 2KB

**Comment by waterfoul** [comment]
Luxon would also be a good alternative

**Comment by GoPro16** [comment]
Luxon would be good as well although its still [16KB](https://bundlephobia.com/result?p=luxon@1.12.0) larger than `dayjs`
