### ISSUE TITLE
Couldn't find package "moment@^2.22.2" required by "availity-reactstrap-validation" on the "npm" registry.

### ISSUE THREAD

**Issue by humbertqz** [Availity/availity-reactstrap-validation#130]
Hi, i wanted to try this library but while installing it the console gave me this error: 

`error Couldn't find package "moment@^2.22.2" required by "availity-reactstrap-validation" on the "npm" registry.`

Does it still works with that error? Thanks for your help.

**Comment by TheSharpieOne** [comment]
The package does exist, both with that exact version and with newer versions within the range allowed:

![image](https://user-images.githubusercontent.com/664714/56438144-ec041480-62af-11e9-89eb-1e5db19adee2.png)

Try `npm doctor` (https://docs.npmjs.com/cli/doctor.html) to make sure you are connecting to the right registry.

**Comment by humbertqz** [comment]
@TheSharpieOne yes i have installed it using this `yarn add moment` and it works. Thanks.
