### ISSUE TITLE
Set default errorMensage for type date 

### ISSUE THREAD

**Issue by jaysongyn** [Availity/availity-reactstrap-validation#133]
```
              <AvGroup>
                <AvField
                  name="date"
                  label="Validade"
                  type="date"
                  errorMessage="Invalid Date"
                  required
                  value={this.props.date}
                  onChange={this.props.handleChange}
                />
              </AvGroup>
```
I try to change the default message "This field is invalid" to "Invalid Date" but no working when the type is date.

**Comment by TheSharpieOne** [comment]
You don't need to wrap `AvField` in `AvGroup` since `AvField` already includes `AvGroup` (as well as a label, the input and error message components plus tying them together).

This is working for me. See: https://stackblitz.com/edit/reactstrap-validation-v2-pe6zjn?file=Example.js

**Comment by jibeetz** [comment]
With the version 2.7.0, an invalid date has its error message reverting to "This field is invalid"
