### ISSUE TITLE
babel-polyfill reference in `index.js` adds to page weight

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-reactstrap-validation#17]
I am profiling the page weight of a React application and noticed `core-js` is one of the big offenders:

```
lodash: 724.25 KB (20.2%)
react-dom: 506.86 KB (14.1%)
core-js: 252.96 KB (7.04%)
availity-uikit: 242.81 KB (6.76%)
```

Removing the `babel-polyfill` reference from [src/index.js#L1](https://github.com/Availity/availity-reactstrap-validation/blob/master/src/index.js#L1) removes `core-js` from the final bundle.

```
lodash: 724.25 KB (21.3%)
react-dom: 506.86 KB (14.9%)
availity-uikit: 242.81 KB (7.16%)
```

Thoughts on removing `babel-polyfill`?  What would you recommend?

**Comment by TheSharpieOne** [comment]
I've already removed it from what will probably be v2 which is a more or less rewrite to improve performance and change the way context work. I've only just started so it will be a little while.  For projects which use the polyfil already it doesn't matter, but this lib shouldn't force people to use it.
