### ISSUE TITLE
Append Text on Button Click

### ISSUE THREAD

**Issue by ArryMatt** [Availity/availity-reactstrap-validation#172]
I have an AvField for units, which works great:

<AvForm model={parameter} onValidSubmit={blah}>
<AvField name="units" label="Units" />
</AvForm>

But often the degrees symbol is needed and nobody knows where or how to do that on a keyboard, so I need to add a button that will append the symbol in on click.  

I was not sure how to do this, as I used jquery to do it, but that gets lost as soon as I submit (newbie fail).  

Do I need to move this field to use state directly (via value and onChange) or is there a better way?

Thanks in advance

**Comment by TheSharpieOne** [comment]
You would have to control the value of the field. You'd need to listen for onChange to update your local state of the value and when the button is clicked update that local state to add the symbol.
Check this demo out: https://stackblitz.com/edit/reactstrap-validation-v2-zvh1qi?file=Example.js

**Comment by ArryMatt** [comment]
Many thanks, works like a dream and the values are correct on submit, which I was unclear if they would be or not.
