### ISSUE TITLE
this.context.FormCtrl is undefined

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-reactstrap-validation#185]
Hey guys,

can someone point me to how to get the form context. 

I have tried something like
https://github.com/Availity/availity-reactstrap-validation/issues/33
 https://stackblitz.com/edit/reactstrap-validation-v2-9hgegg?file=Example.js
https://github.com/Availity/availity-reactstrap-validation/issues/103
https://github.com/Availity/availity-reactstrap-validation/issues/92
and 
https://github.com/Availity/availity-reactstrap-validation/issues/29

```
@observer
export default class Inquiry extends Component {
  constructor(props) {
    super(props);

    this.form = createRef();
  }

  render() {
    return (
      <Card>
        <CardBody>
          <AvForm onValidSubmit={this.submit} ref={this.form}>
          ... fields go here
          </AvForm>
        </CardBody>
      </Card>
    );
  }
}

```
What I'm trying to accomplish is reset the form on submit, as well as be able to reset some fields based on user interaction. 
any help will be highly appreciated.

**Comment by TheSharpieOne** [comment]
It's `ref` vs `context`. You are getting a ref, and you should be able to use that ref to get the context via `this.form.current.getChildContext().FormCtrl`. That will give you access to the context as defined here: https://github.com/Availity/availity-reactstrap-validation/blob/ec3062beddaa8bb36ca19b4c147d7bf9c1a7d5fc/src/AvForm.js#L130-L148

The context just exposes many of the form methods you could access directly on the ref. If you wanted to reset a specific field you can do `this.form.current._inputs[inputName].reset()`
Check out https://stackblitz.com/edit/reactstrap-validation-v2-42indb?file=Example.js

You can do this in a loop with different `inputName` values to affect more fields and you can trigger it in your onValidSubmit callback.

**Comment by diegodesouza** [comment]
@TheSharpieOne excellent thank you for the example

**Comment by diegodesouza** [comment]
@TheSharpieOne this approach doesn't seem to be working on `AvSelectField`, how would you go about reseting one?

**Comment by MJSHANZ** [comment]
@TheSharpieOne  -  I am having a small roadblock in implementing the same for Date field. Please find the details below and please let me know incase if there is any valid work around.

**Scenario:**  If I enter the date and remove either MM or DD or YYYY, then I am seeing validation error - "This field is invalid" and here I am able to reset only the validation error but the not the value in the input filed. Is there is work around to reset the Date Field as a whole(validation errors and input value)

Screenshot: 1 - 

![image](https://user-images.githubusercontent.com/101058458/175339346-ca5cd48d-bb38-443b-b638-d2d675d812c9.png)


Screenshot: 2 - 

![image](https://user-images.githubusercontent.com/101058458/175342374-28b8c50e-95bf-47c5-bad9-0d7f7b7ee9bb.png)


Screenshot: 3 -  Here if I click "Reset Date Field", the validation is removed but I still see the value in the input field 06/dd/2022 (highlighted in red color box)

![image](https://user-images.githubusercontent.com/101058458/175342968-83fae6a4-ac31-4b74-995c-149d02d88cab.png)
