### ISSUE TITLE
How add custom errors messages ?

### ISSUE THREAD

**Issue by hilde2** [Availity/availity-reactstrap-validation#19]
Hi,

How handle custom errors message ?

Let's say we have a unsername filed : 
`  <AvGroup> `
    `<Label for="username">UserName</Label>`
    `<AvInput name="username" id="username" required minLength="6" maxLength="16" validate={{pattern: {value: '^[A-Za-z0-9]+$'}}} />`
    `<AvFeedback>UserName is not valid</AvFeedback>`
  `</AvGroup>`

I want to have errors like 
- "Your username must be between 6 and 16 characters" 
- "Your username must be composed only with letter and numbers"

How I easly do this with this lib ?

**Comment by TheSharpieOne** [comment]
If you use `<AvField>`, which handles the group, label, input, and feedback for you, you can use the `errorMessage` prop or provide individual `errorMessage`s on the validate object.
```
<AvField name="username" required validate={{
  pattern: {value: '^[A-Za-z0-9]+$', errorMessage: 'Your username must be composed only with letter and numbers'},
  minLength: {value: 6, errorMessage: 'Your username must be between 6 and 16 characters'},
  maxLength: {value: 16, errorMessage: 'Your username must be between 6 and 16 characters'},
}}

Currently, if you want to have custom error messages, you need to use the `validate` prop to define the validation value and the errorMessage. It would be nice if there was a way to keep the HTML5 validation attribute props and also define the custom error messages. I'll keep this in mind for v2.

**Comment by taymoor89** [comment]
This didn't worked for me. If I put `errorMessage` just like you mentioned above, it doesn't come through.

**Comment by TheSharpieOne** [comment]
See this demo:
https://www.webpackbin.com/bins/-KejZeqs1swMCz4aF0zQ
preview:
![validation-errormessage](https://user-images.githubusercontent.com/664714/30178583-78c48aa2-93d7-11e7-8fe5-fbc8a09e3c39.gif)

Here is the code:
```jsx
import React from 'react';
import { Container } from 'reactstrap';
import { AvForm, AvField } from 'availity-reactstrap-validation';

class AvailityReactstrapValidationExample extends React.Component {
  render() {
    return (
      <Container className="py-4">
        <AvForm>
          <AvField name="username" label="Username" validate={{
              required: {value: true, errorMessage: "Please enter a username"},
              pattern: {value: '^[A-Za-z0-9]+$', errorMessage: 'Your username must be composed only with letter and numbers'},
              minLength: {value: 6, errorMessage: 'Your username must be between 6 and 16 characters'},
              maxLength: {value: 16, errorMessage: 'Your username must be between 6 and 16 characters'}
          }} />
          
          <AvField name="password" label="Password" type="password" required
            errorMessage="This error message is generic and gets overriden by the ones provided in the validate prop as those are more specific to a particular validation"
            validate={{
              pattern: {value: '^[A-Za-z0-9]+$', errorMessage: 'Your username must be composed only with letter and numbers'},
              minLength: {value: 6, errorMessage: 'Your username must be between 6 and 16 characters'},
              maxLength: {value: 16, errorMessage: 'Your username must be between 6 and 16 characters'}
          }} />
        </AvForm>
      </Container>
    );
  }
}
export default AvailityReactstrapValidationExample
```

**Comment by AlpeshMN** [comment]
@TheSharpieOne , can you please share some information related to "Searchable/Sortable Dropdown fields" within above code given by you. Looking for orderby example too in order to sort data in it. Thanks
<img width="1225" alt="screen shot 2018-07-05 at 2 02 30 pm" src="https://user-images.githubusercontent.com/37811280/42339818-23cf0ca8-805c-11e8-99e3-b433f5e74e3e.png">

**Comment by jrogelj** [comment]
Hi, is it possible to translate multiple error messages with react-intl or something similar?

**Comment by AbhaysinghBhosale** [comment]
i think reported issue is for AvInput instead of using AVField because in my case i want to attach copy icon with field but with av field that is not possible
