### ISSUE TITLE
focus AvInput on load

### ISSUE THREAD

**Issue by mstruensee** [Availity/availity-reactstrap-validation#195]
is there a way to focus an input on page load, this is what I have tried, focus() exists, but its not focusing ... do I need to force a re-render inside AV??
`const inputRef = useRef(null);`
`useEffect(() => inputRef.current.focus(), [])`
`<AvInput name={ "foo" } type={ "text" } required getRef={ inputRef } />`

**Comment by TheSharpieOne** [comment]
what about `autofocus`?
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/autofocus

**Comment by mstruensee** [comment]
:doh: guess I was overthinking it ... thanks!
