### ISSUE TITLE
How to Reset the form after submit (w/ React Hooks)

### ISSUE THREAD

**Issue by JanderSilv** [Availity/availity-reactstrap-validation#200]
I've seen the example of how to reset the form with classess and "ref" but I would like to know how to do it with React Hooks.

**Comment by SNikhill** [comment]
Greetings @JanderSilv ,
I am not sure if I understand your question. could you please elaborate it?
Also, if by "ref" you mean useRef hook then, I think, you already have the question your problem.

Regards
SNikhill

**Comment by JanderSilv** [comment]
Hello @SNikhill, thanks for responding. Actually I don't remember why I had that doubt in that time, probably I didn't know how to use the useRef's hook yet. But the problem was solved, the project already finished and this issue can be closed. Thanks again.

**Comment by SNikhill** [comment]
Greetings @JanderSilv,
Good to hear that your problem has been solved. 
You will have to close the issue from your end.

Regards
SNikhill
