### ISSUE TITLE
textareas?

### ISSUE THREAD

**Issue by pankajpatel** [Availity/availity-reactstrap-validation#21]
Support for textareas?

**Comment by pankajpatel** [comment]
nevermind; I tried with `type="textarea"` on `AvInput` as:
```jsx
<AvInput type="textarea" name="address" id="address" placeholder="Address" required />
```

and it worked.

Thanks.

**Comment by TheSharpieOne** [comment]
Yeah, type is the key. It also works with type of "select" with option(s) as children

**Comment by pankajpatel** [comment]
can I add more documentation code for this?

**Comment by TheSharpieOne** [comment]
Go for it. Right now the documentation is more by example (showing various inputs in a form) and not really going over the individual inputs. Feel free to add a page dedicated to `textarea`, showcasing how to default values and all. Same for `select` if you are up for the task.
