### ISSUE TITLE
How to use another button in the form

### ISSUE THREAD

**Issue by LoanAubergeon** [Availity/availity-reactstrap-validation#211]
I want to use another button (not submit button) to do a action in the form. 
When I click on the button, the form is submitted..
How to do that ?

**Comment by TheSharpieOne** [comment]
Give it a type of "button" (`type="button"`). If you are using reactstrap's `Button`, simply handling the click (via `onClick` function) will have reactstrap set the type to `"button"`.

HTML default is submit. Check out: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.

**Comment by LoanAubergeon** [comment]
I did not give the type "button" to the reactstrap's Button.
