### ISSUE TITLE
How to mention a red asterisk in the label for telling the user that the input is compulsory before clicking the button.

### ISSUE THREAD

**Issue by shvamabps** [Availity/availity-reactstrap-validation#215]
Is it possible to use inline CSS by which one can modify the label attribute of the form?

**Comment by nylon22** [comment]
Hi @shvamabps the prop type for `label` is a `node`, meaning you can pass in any JSX for the label prop, including a red asterisk.

**Comment by shvamabps** [comment]
@nylon22  thanks for the solution. It worked
