### ISSUE TITLE
Get all the values of AvForm without submit button

### ISSUE THREAD

**Issue by hungdev** [Availity/availity-reactstrap-validation#220]
is there any way to get all the values of AvForm without using submit button, for example get values via ref....

**Comment by hungdev** [comment]
I found out. use `this.form.getValues()`
Example for who want to know: 
https://codesandbox.io/s/romantic-hooks-ky9o2?file=/src/App.js:766-787
and beside that i found more useful func. Look at the image.
![image](https://user-images.githubusercontent.com/12009276/102851427-58a0c080-444e-11eb-840a-dc3600a6afa8.png)

**Comment by AbhaysinghBhosale** [comment]
Is there any way to get it working for select input. As i did used "this.formRef.current.getValues()" which does not return value of select dropdown.

`<AvField type="select" id="Role" name="Role" label={Resource.lblUserRole} value={this.state.User && this.state.User['Role']} required>
                                            <option value="">SelectRole</option>
                                            <option value="Admin">UserRoles1</option>
                                            <option value="Reader">UserRoles2</option>
                                        </AvField>`

i do get values in onKeyDown={this.onKeyDown} method to detect if values in form and original values are updated
