### ISSUE TITLE
How do I know which button is being clicked

### ISSUE THREAD

**Issue by hungdev** [Availity/availity-reactstrap-validation#222]
i have 2 buttons with type="submit". How do I know which button is being clicked?

```
<AvForm onSubmit={onSubmit}>
   <AvField name="name" label="Name" required />
   <Button type='submit' name='save'>Save </Button>
   <Button type='submit' name='next'>Next </Button>
</AvForm>
```

```
const onSubmit = (event, errors, values) => {
   console.log(event.target.name)
}
```

i tried to get event.target.name in onSubmit function, but it cannot get button name.
thank you

**Comment by SNikhill** [comment]
Greetings @hungdev,
Did you try giving each of the button a unique id and then, accessing that id to identify the button?

Regards
SNikhill

**Comment by hungdev** [comment]
so onSubmit func how do i get it? @SNikhill

**Comment by SNikhill** [comment]
Hey,
I am not sure if you can access the button that called the submit using `onSubmit` but, you can achieve the same by adding an additional click handler on both of the buttons and then, in that case, the `event` will refer to the button that got clicked and you will be able to access the `id` of the button. 
If you want, we can try this out together. Here is my discord id: `SNikhill#0437`.

Regards
SNikhill

**Comment by hungdev** [comment]
@SNikhill Thank for your reply.
I want to get id of Button in `onSubmit`, because I want to handle the instances of each button.
I created an codesanbox example, can you edit it?
https://codesandbox.io/s/dazzling-wave-356b8?file=/src/App.js
Thank you.

**Comment by SNikhill** [comment]
Greetings @hungdev, 
[This is what I meant](https://codesandbox.io/s/forhungdev-sgd83)
I am kind of getting a hunch that you don't need 'next' to be a submit.
Here is my discord id: `SNikhill#0437`. We can have a chat there.

Regards
SNikhill

**Comment by hungdev** [comment]
@SNikhill,  I think you misunderstood me. i want to get id of button in onSubmit func ( not outside ).
Please take a look to line 9 -> 15
![image](https://user-images.githubusercontent.com/12009276/103188119-c55a0600-48f9-11eb-9146-dec9487b5028.png)

**Comment by SNikhill** [comment]
Hey @hungdev,
Yes, I get what you want. I have updated the example to better suit your use case. [See it Here](https://codesandbox.io/s/forhungdev-sgd83?file=/src/App.js).

Regards
SNikhill

**Comment by SNikhill** [comment]
Sorry, I forgot to save the file. Check the link again.

**Comment by hungdev** [comment]
@SNikhill
I got it. Thank you so much.
![image](https://user-images.githubusercontent.com/12009276/103197099-03feb900-4918-11eb-9303-72b5285c2573.png)

**Comment by SNikhill** [comment]
Greetings @hungdev ,
How are you?
I actually found another way. Turns out that the [SubmitEvent](https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent) keeps a record of the submitter.

Try this out:
```js
onSubmitHandler = (event) => console.log(event.naturalEvent.submitter.name)
```
This way, you won't have to use an external variable. 
 
 I hope that this helps.
 
 Regards
 SNikhill

**Comment by hungdev** [comment]
@SNikhill great!
I think using `SubmitEvent`  is the best way. That's my expectation.
Thank you again :)
