### ISSUE TITLE
react-18 peer-dependency

### ISSUE THREAD

**Issue by astriskit** [Availity/availity-reactstrap-validation#267]
Hello there.

Is this a react-18 safe library? Idk, btw! :)

If so, the peer-dependency needs to be updated.

**Comment by jordan-a-young** [comment]
Hello. This package is no longer maintained. We have another form library that is actively maintained

https://github.com/Availity/availity-reactstrap-validation#important-update---4th-january-2021

**Comment by astriskit** [comment]
cool, thanks for the prompt reply.
