### ISSUE TITLE
AvRadio model when using boolean values

### ISSUE THREAD

**Issue by KaseyPowers** [Availity/availity-reactstrap-validation#38]
I have a simple radio group with a Yes/No option tied to boolean true/false like so:
```
<AvRadioGroup label="A question" name="exampleGroup">
  <AvRadio label="Yes" value id="example_yes"/>
  <AvRadio label="No" value={false} id="example_no"/>
</AvRadioGroup>
```
If I give a model value to the AvForm with `true` than the option is selected correctly, but if If I give it `false` than the second radio is not selected.

**Comment by KaseyPowers** [comment]
This difference might be what causes it?

https://github.com/Availity/availity-reactstrap-validation/blob/master/src/AvRadioGroup.js#L90
vs.
https://github.com/Availity/availity-reactstrap-validation/blob/master/src/AvBaseInput.js#L147

**Comment by GoPro16** [comment]
Should be fixed in the latest version: 
https://codesandbox.io/s/reactstrap-validation-issue-38-que4c
