### ISSUE TITLE
Low Performance in IE11

### ISSUE THREAD

**Issue by ArbanNichols** [Availity/availity-reactstrap-validation#43]
I really enjoy the ease of use this library has but it comes with a steep performance price in IE. Is there any way around this issue?

**Comment by TheSharpieOne** [comment]
Most of the components are fairly simple; only adding classes. Any particular component causing this issue?

**Comment by TheSharpieOne** [comment]
Duplicate of #14

**Comment by ArbanNichols** [comment]
AvInput is very slow with each keystroke. This is only an issue in IE.
Chrome and FF don't seem to have an issue.

**Comment by GoPro16** [comment]
IE has always had low performance on the DOM renders. Closing and reference #14 for any updates to performance.
