### ISSUE TITLE
Reactstrap and bootstrap versions

### ISSUE THREAD

**Issue by brvins** [Availity/availity-reactstrap-validation#44]
I am trying to implement Availity reactstrap validation for react app. Validations work fine with Reactstrap version 4.6.2 but with latest version of reactstrap we are not able to see the error message and red border for the input fields(but when we inspect we see correct css class changes) . Can any one tell which version of reactstrap and bootstrap should we use with this library.

**Comment by brvins** [comment]
The below versions solved the issue
"availity-reactstrap-validation": "^2.0.0-alpha.0",
    "bootstrap": "^4.0.0-alpha",
    "react": "^16.1.1",
    "react-dom": "^16.1.1",
    "react-scripts": "1.0.17",
    "reactstrap": "^5.0.0-alpha.4"

**Comment by pihomeserver** [comment]
Thanks @brvins 

Works also with 
"bootstrap": "4.0.0-beta.2"
