### ISSUE TITLE
Error in 2.0.0-alpha.0 version on form submit

### ISSUE THREAD

**Issue by prasadmes** [Availity/availity-reactstrap-validation#47]
Hi

I am getting the  following warning on form submit in my console. 

Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the AvForm component.

**Comment by prasadmes** [comment]
I am dispatching form submit event which calls other component. But AvForm does some state stages after forrm submit

**Comment by TheSharpieOne** [comment]
It's not an error just a warning which results in a harmless no-op

**Comment by prasadmes** [comment]
Yes. But cant it be avoided? @TheSharpieOne

**Comment by TheSharpieOne** [comment]
Not in the current version. It is something that will be addressed in the planned rewrite.

**Comment by GoPro16** [comment]
closed via #144
