### ISSUE TITLE
Is field depends on another field supported.

### ISSUE THREAD

**Issue by NoelJames** [Availity/availity-reactstrap-validation#48]
is there a way to validate in that,  a field is required depending on the value of another field?

I have a form like the following where, if the checkbox `love_it` is checked the user doesn't need to enter any value in textarea `no_love` but, they can. If not checked an error message should indicate that they need to love_it or tell why they have no_love.

https://www.webpackbin.com/bins/-L058nKuy5RDv_jwud6a

**Comment by TheSharpieOne** [comment]
You can use a custom validation function https://www.webpackbin.com/bins/-L05Gs7knBORAkgWnqqP

The function is passed the field value and a context object which contains the other fields in the form. Using those you can determine if the field is valid. Returning false or a string error message will make the field invalid. If you return the string error message, that error message will be displayed.

The only downside is that while the textarea's validation depends on the checkbox, changing the checkbox does not cause the textarea to be re-validated, only changing the textarea (which validates only the textarea) and submitting the form (which validates all of the fields) trigger that.

You can handle that case by getting a ref to the form and trigging the validation when the checkbox is changed: https://www.webpackbin.com/bins/-L05HsI_uMn3hTYEbOy8

**Comment by NoelJames** [comment]
IDK, if this is obvious but, this is a fantastic solution `validate={{customValidation}}`!

Thanks!

**Comment by TheSharpieOne** [comment]
Yeah, the docs for custom validation functions are not that great, only giving the one example and not really explaining much, sorry :(

**Comment by NoelJames** [comment]
New to the modern javascript and this it so much better then the hack i was working out.

:beers:

**Comment by hungdev** [comment]
anyone have an codesanbox example?

**Comment by TheSharpieOne** [comment]
https://stackblitz.com/edit/reactstrap-validation-v2-dfzfsc?file=Example.js

```jsx
import React, { Component } from 'react';
import { Button, Label, FormGroup } from 'reactstrap';
import { AvForm, AvField, AvGroup, AvInput, AvRadioGroup, AvRadio, AvFeedback } from 'availity-reactstrap-validation';

class Example extends Component {
  state = {};
  onValidSubmit = (event, values) => {
    this.setState({errors: null, values});
  };
  onInvalidSubmit = (event, errors, values) => {
    this.setState({errors, values});
  };
  // value: current value of the field to be validated
  // ctx: "context", the form object containing other fields by name
  // input: raw access to the input element
  // cb: callback, to be used if you need to perform async work.
  myCustomValidation = (value, ctx, input, cb) => {
    // access other fields by name via ctx
    if (ctx.myCheckbox) {
      // returning a string indicates "validation fail" and the string will be used as the error message
      // returning false indicates "validation fail"
      return !!value || 'You checked the box, now fill out this field';
    }
    // returning true indicates "validation pass"
    return true;
  }
  render() {
    const { errors, values } = this.state;
    return (
      <div>
        <AvForm onValidSubmit={this.onValidSubmit} onInvalidSubmit={this.onInvalidSubmit}>
          <AvField label="Make other field required" name="myCheckbox" type="checkbox" />
          <AvField label="Email Address" name="email" type="email" validate={{myCustomValidation: this.myCustomValidation}} />
          <Button>Submit</Button>
        </AvForm>
        <br />
        {errors && errors.length && <pre>Errors: {JSON.stringify(errors, null, 2)}</pre>}
        {values && <pre>Values: {JSON.stringify(values, null, 2)}</pre>}
      </div>
    )
  }
}

export default Example;
```
