### ISSUE TITLE
How to pass extra data apart from values in AvForm onValidSubmit?

### ISSUE THREAD

**Issue by lambotchi** [Availity/availity-reactstrap-validation#49]
You can access the AvField values in onValidSubmit but how to pass an extra data so I can access it on `onValidSubmit(event, values){}` ? I have a stateless functional SignUpFormComponent. There is a confirmationCode AvField and a username from the properties

**Comment by TheSharpieOne** [comment]
You can use inputs with type of hidden. These are just inputs which do not get shown to the user and are typically used for storing and passing data around.
Though I would that the onValidSubit just have access to those extra values in scope instead of using the DOM store and pass data around.

**Comment by legnoban** [comment]
i was also considering that before. I'm thinking if it's possible to bind `username` as third paramter after `event` and `values`. Is that possible? i don't have idea how to implement [this answer](https://stackoverflow.com/questions/27699493/javascript-partially-applied-function-how-to-bind-only-the-2nd-parameter)

**Comment by GoPro16** [comment]
Yes you can create a custom `onSubmit` function and bind your scope to it if you are really wanting to. Otherwise you should just pass it down in the props:

ex1:

```
const onSubmit = (event,values) => {
 console.log(this.username);
}

return <AvForm onValidSubmit={onSubmit.bind({ username })>
...
</AvForm>
}
```

ex2:
const Form = ({ username }) => (
<AvForm />
)
