### ISSUE TITLE
validate onSubmit only

### ISSUE THREAD

**Issue by mstruensee** [Availity/availity-reactstrap-validation#51]
on initial load of page its fine, no red boxes, redux resets the state to original values and its rendered with errors / red boxes.  any way to validate only onSubmit vs lose focus or initial load or suggestions to prevent this??

any way to do a reset the values/clear them out?

**Comment by TheSharpieOne** [comment]
If you set validationEvent on AvForm to an empty array, it should prevent it from validating on individual field events. The only validation then would be on submit.

You can reset the fields values and validation by getting a ref to AvForm and calling reset() on the ref. Reset will reset the fields back to the default values from the model or defaultValues passed in.

**Comment by mstruensee** [comment]
setting validationEvent={[]}  did not seem to do the trick ...

also, im using 2.0.0-alpha.1

**Comment by TheSharpieOne** [comment]
Looking closer are the code, there doesn't appear to be a way to do that and change validationEvent actually breaks things 😞 . 
I'll have to keep this in mind for the rewrite.

**Comment by mstruensee** [comment]
Thanks!  I redesigned the page to redirect after success so I "have a work around".  This would be a nice feature though!

check out #55 if u can :D ... that is a blocker for me at the moment.
