### ISSUE TITLE
Does this not work with the latest version of reactstrap?

### ISSUE THREAD

**Issue by webbygregg** [Availity/availity-reactstrap-validation#52]
I have tried many of the examples in the docs but I only seem to get color="danger" added to the form group when invalid. It doesn't seem to add the valid=true/false prop.

**Comment by TheSharpieOne** [comment]
you have to use `availity-reactstrap-validation@next` with `reactstrap@next`

**Comment by webbygregg** [comment]
Awesome, thank you, it's working now
