### ISSUE TITLE
Custom Error Messages with Async?

### ISSUE THREAD

**Issue by webbygregg** [Availity/availity-reactstrap-validation#53]
Is it possible to send custom error messages using async: this.validate ?

I tried validate={ aysnc: {value: this.validate, errorMessage: 'Wrong'}}

and I tried in the callback

cb({value: false, errorMessage: 'Wrong' })
 
Also with async, it only seems to validate once i have focused away from the field. How can I run it while typing?

**Comment by TheSharpieOne** [comment]
If your custom validation returns a string, that string will be the error message.

All of the validations are ran as the same time, the trigger to run the validation is determined by the `validationEvent`, which by default is `['onChange', 'onInput']` which would be while typing. Note, that with AvField the initial validation message doesn't displaying until the field has been "touched", which is triggered by blurring the field, but validation does run with every keystroke before that. If you use AvInput with reactstrap's FormGroup, Label, and FormFeedback directly, you can control when the UI changes (this library will still handle the validation, but is less useful this way).

**Comment by webbygregg** [comment]
Thanks again for your help, it's working now
