### ISSUE TITLE
Warning: Received `false` for a non-boolean attribute `valid`.

### ISSUE THREAD

**Issue by vndevil** [Availity/availity-reactstrap-validation#54]
This is my code and I have this error: Warning: Received `false` for a non-boolean attribute `valid`.

If you want to write it to the DOM, pass a string instead: valid="false" or valid={value.toString()}.

If you used to conditionally omit it with valid={condition && value}, pass valid={condition ? value : undefined} instead.

`import React from 'react';
import AdminComponent from '../Components/AdminComponent.jsx';
import {
    Row,
    Card,
    CardHeader,
    CardFooter,
    CardBlock,
    Col,
    Button,
    Form,
    FormGroup,
    Label,
    Input,
    FormText
} from 'reactstrap';
import { AvForm, AvField, AvGroup, AvInput, AvFeedback, AvRadioGroup, AvRadio } from 'availity-reactstrap-validation';
import { Button_Edit, Button_Reset } from '../WebControls/AllControls.jsx';
import axios from 'axios';
import DateTimeHelper from '../../../../Server/Helpers/DateTimeHelper.jsx';
import ConvertHelper from '../../../../Server/Helpers/ConvertHelper.jsx';

class Users_Password extends AdminComponent {
    constructor(props) {
        super(props);

        this.state = {
            user: {}
        };

        this.onChange = this
            .onChange
            .bind(this);
        this.onSubmit = this
            .onSubmit
            .bind(this);
    }

    componentDidMount() {
        // Get data
        var id = this.QueryStringId(this.props.location.search);
        //console.log('_id:' + id);
        if (id) {
            // Get user from database
            axios
                .get('/api/users?_id=' + id)
                .then((response) => {
                    this.setState({ user: response.data[0] });
                    //console.log(this.state.user);
                });
        }
    }

    onChange(event) {
        event.persist();

        const inputName = event.target.name; // Lấy về name của <input name='username' />
        const inputValue = event.target.value; // lấy về value của <input name='username' />

        const user = this.state.user;
        user[inputName] = inputValue;

        this.setState({ user });
    }

    onSubmit(event) {
        event.persist();
        const password = encodeURIComponent(this.state.user.Password);
        if (password && password != 'undefined') {
            console.log('password: ' + password);
        }
    }

    render() {
        return (
            <div className="animated fadeIn">
                <Col lg="6" xs="12" className="nopadding">
                    <AvForm onValidSubmit={this.onSubmit}>
                        <Card>
                            <CardHeader>
                                <i className="fa fa-lg fa-table"></i>
                                <strong>Thay đổi mật khẩu: {this.state.user.UserName}</strong>
                            </CardHeader>
                            <CardBlock className="card-body">
                                <Col xs="12">
                                    <Row>
                                        <Col md="6" xs="12">
                                            <FormGroup>
                                                <Label className="font-weight-bold">Ngày tạo</Label>
                                                <Input
                                                    value={DateTimeHelper.FormatDate(this.state.user.CreatedDate)}
                                                    disabled />
                                            </FormGroup>
                                        </Col>
                                        <Col md="6" xs="12">
                                            <FormGroup>
                                                <Label className="font-weight-bold">Ngày chỉnh sửa</Label>
                                                <Input
                                                    value={DateTimeHelper.FormatDate(this.state.user.ModifiedDate)}
                                                    disabled />
                                            </FormGroup>
                                        </Col>
                                    </Row>
                                    <FormGroup>
                                        <Label className="font-weight-bold">Tên đăng nhập</Label>
                                        <Input
                                            value={ConvertHelper.ToString(this.state.user.UserName)}
                                            disabled />
                                    </FormGroup>
                                    <FormGroup>
                                        <Label for="Password" className="font-weight-bold">Mật khẩu</Label>
                                        <AvGroup>
                                            <AvField
                                                type="password"
                                                placeholder="Mật khẩu mới"
                                                name="Password"
                                                onChange={this.onChange}
                                                autoComplete="off"
                                                minLength="8"
                                                maxLength="25"
                                                required />
                                        </AvGroup>
                                    </FormGroup>
                                    <FormGroup>
                                        <Label for="RePassword" className="font-weight-bold">Xác nhận mật khẩu</Label>
                                        <AvGroup>
                                            <AvField
                                                type="password"
                                                placeholder="Xác nhận mật khẩu mới"
                                                name="RePassword"
                                                onChange={this.onChange}
                                                autoComplete="off"
                                                required
                                                validate={{
                                                    match: {
                                                        value: 'Password',
                                                        errorMessage: 'Xác nhận mật khẩu không đúng !!!'
                                                    }
                                                }}
                                            />
                                        </AvGroup>
                                    </FormGroup>
                                </Col>
                            </CardBlock>
                            <CardFooter>
                                <Button_Edit />
                                <Button_Reset />
                            </CardFooter>
                        </Card>
                    </AvForm>
                </Col>
            </div>
        )
    }
}

export default Users_Password;`

**Comment by TheSharpieOne** [comment]
What version of reactstrap and availity-reactstrap-validation are you using?
Base on the error message, it looks like you need to update the version of reactstrap you are using.

**Comment by vndevil** [comment]
I'm using:

react ^16.2.0
reactstrap ^4.8.0
availity-reactstrap-validation ^2.0.0-alpha.1

**Comment by TheSharpieOne** [comment]
You need reactstrap@5.0.0-alpha.4 or higher for 2.0.0-alpha.0 or higher. That is where reactstrap added the `valid` prop which this library uses.

**Comment by vndevil** [comment]
thank you, I was run "npm update" to update reactstrap, the problem resolved
