### ISSUE TITLE
onKeyDown Enter to submit form

### ISSUE THREAD

**Issue by mstruensee** [Availity/availity-reactstrap-validation#55]
When I add a 2nd input text, this no longer works.  it only works when I have one.  How can I make this work no matter how many I have in my form?

using 2.0.0-alpha.1

**Comment by TheSharpieOne** [comment]
This is not an issue with this library, but how the browser works. The browser handles submitting the form when enter is pressed. It is known that when a single input field is present you don't need a button within the form to allow it to be submitted, but when multiple fields are present, you need a button (or input type=submit) to allow the form to be submitted via enter.

This is per the HTML spec: https://www.w3.org/MarkUp/html-spec/html-spec_8.html#SEC8.2

> When there is only one single-line text input field in a form, the user agent should accept Enter in that field as a request to submit the form.

Again, this is handled by the browser, not this library so there is nothing this library is doing to make  it work this way and nothing this library will do to make it work differently.

Things can you do is add a submit button and visually hide it or add a key press listener to capture the enter key and do stuff then.

**Comment by mstruensee** [comment]
adding type={'submt'} to my button solved the problem.  Thanks for the browser 101 lesson!!!
