### ISSUE TITLE
Delayed Field Validation

### ISSUE THREAD

**Issue by kdmessner** [Availity/availity-reactstrap-validation#57]
I am using AvField to validate an NPI number. I saw that I could specify the validationEvent and I currently have it set to onBlur which works as expected. I would also like it to run the validation if the user has not typed anything into the currently focused field after some amount of time. I saw that this is happening on some of the other Angular apps on Availity and so I was curious if I was just missing something with the React components or if this feature has not been made in React yet.

Thank you

**Comment by andrueandersoncs** [comment]
@kdmessner it seems what you want is a "onKeyUp" validation handler, not a timeout validation handler. If you validate all input on key up you know for sure that any input in the field is valid; there becomes no need for a timeout / interval based solution.

**Comment by kdmessner** [comment]
@andrueandersoncs `onKeyUp` is not satisfactory for this use case. We do not want the error messages to show up every time the input changes. We want it to show when we know the user has finished typing. Our UX team has deemed this to be `onBlur` and after a delay. `onBlur` is easy enough, however there does not seem to be an explicit option for a delayed validation. 

If this is a feature that is not supported by this package then that is fine. I just wanted to make sure I wasn't missing anything since our testing team believes they had seen delayed validation functionality on other Availity applications.

**Comment by tobia** [comment]
You can trigger your validation `onKeyUp`, but wrap the validation code in a debouncer, such as NPM module `debounce`. This way, every key up flags the validator to be run, but it waits a number of seconds before doing that, in case the user is still typing.

    {
      validator: debounce((value, ctx, input, callback) => {
        ...
      })
    }

**Comment by GoPro16** [comment]
Closing this issue, please re-open if you are still having issues. We also have a new form library built on top of `formik` coming soon that you can hook into much easier.
