### ISSUE TITLE
Cannot validation with sub props

### ISSUE THREAD

**Issue by vndevil** [Availity/availity-reactstrap-validation#58]
Hi guy,

I cannot validate with AvField name: "Local.Password"

`<AvForm onValidSubmit={this.onSubmit}>
<FormGroup>
                        <Label for="Password" className="font-weight-bold">Mật khẩu</Label>
                        <AvGroup>
                            <AvField
                                type="password"
                                placeholder="Mật khẩu mới"
                                name="Local.Password"
                                onChange={this.onChange}
                                autoComplete="off"
                                validate={{
                                    required: {
                                        value: true,
                                        errorMessage: 'Bạn chưa điền mật khẩu !!!'
                                    },
                                    minLength: {
                                        value: '8',
                                        errorMessage: 'Mật khẩu ít nhất 8 ký tự !!!'
                                    },
                                    maxLength: {
                                        value: '25',
                                        errorMessage: 'Mật khẩu nhiều nhất 25 ký tự !!!'
                                    }
                                }}
                            />
                        </AvGroup>
                    </FormGroup>
                    <FormGroup>
                        <Label for="RePassword" className="font-weight-bold">Xác nhận mật khẩu</Label>
                        <AvGroup>
                            <AvField
                                type="password"
                                placeholder="Xác nhận mật khẩu mới"
                                name="RePassword"
                                autoComplete="off"
                                validate={{
                                    match: {
                                        value: 'Local.Password',
                                        errorMessage: 'Xác nhận mật khẩu không đúng !!!'
                                    }
                                }}
                            />
                        </AvGroup>
                    </FormGroup>
</AvForm>`

**Comment by vndevil** [comment]
noone can help me?

**Comment by TheSharpieOne** [comment]
Sorry, I looked into this and it is an issue with the match validation not using `get` to pull the value out of the context object.

Also, you code could be simplified, there is no need to use reactstrap's `FormGroup` with `AvGroup` and there is no need to use `AvGroup` with `AvField`, you can just use `AvField` with the `label` prop and use the `labelAttrs` prop to add the extra `className`
See this example for that: https://stackblitz.com/edit/reactstrap-validation-alpha-starter-bmqweq?file=Example.js
