### ISSUE TITLE
option crashing browser when 2 on screen using redux

### ISSUE THREAD

**Issue by mstruensee** [Availity/availity-reactstrap-validation#63]
I have a reusable component that is looping options for a select input.  when I have 2 of them on the same screen that fetch data using redux, it crashes chrome.  I switch them to reactstrap inputs and they work fine.

on a different project i have 2 on the same screen but i have the options hardcoded, works fine.
it seems to choke when a 2nd "dynamic" one is added.

if 1 is reacstrap input, 1 avinput ... works fine

i have no output, just a browser freezing/crashing ... sorry ...

edit: this is also happening now with 1 checkbox and 1 select.

**Comment by TheSharpieOne** [comment]
Can you try with the latest v2 release (using `npm i availity-reactstrap-validation@next`)

**Comment by GoPro16** [comment]
If you are still having issues feel free to create a codesandbox to replicate it. Most likely a later version of `availity-reactstrap-validation` works for your use case.
