### ISSUE TITLE
Moment version exact?

### ISSUE THREAD

**Issue by flipxfx** [Availity/availity-reactstrap-validation#64]
Is there a reason the moment version is exactly 2.18.1? This is causing bloat when trying to use moment outside of the this module and not using that exact version. It should actually probably be a peer dependency.

**Comment by TheSharpieOne** [comment]
I goes back to moment broke everything: https://github.com/moment/moment/issues/4216
Probably need to unpin it now.

**Comment by flipxfx** [comment]
I'm for it!

**Comment by TheSharpieOne** [comment]
This is fixed in the latest beta release
