### ISSUE TITLE
input type="tel" invalidates field for any input

### ISSUE THREAD

**Issue by kevalmalde** [Availity/availity-reactstrap-validation#72]
input type="tel" invalidates field for any input

For example.
Example given in below link for Phone number, shows error message for any input value
https://availity.github.io/availity-reactstrap-validation/components/validators/

**Comment by TheSharpieOne** [comment]
By default, this validation only accepts phone numbers allowed in the NANP (North America Numbering Plan). A valid NANP number is 10 digits long, cannot start with a 0 or 1, and some other rules. The pattern used can be overridden to work with other country's numbering plans.

**Comment by georgiosd** [comment]
@TheSharpieOne how do we override that? Using a pattern validator you mean?

**Comment by TheSharpieOne** [comment]
That or you can provide a pattern to the `tel` validation (which for now just passes that to the `pattern` validation mentioned above) In the future there may be a better way to know which particular validation failed so there would be a difference between using `pattern` directly and using `tel` providing a pattern.

https://stackblitz.com/edit/availity-reactstrap-validation-72-rjv6st?file=Example.js

```jsx
<AvField name="telephone" label="Phone" type="tel" validate={{tel: {pattern: REGEXP}}} />
```
