### ISSUE TITLE
Validation involving multiple fields

### ISSUE THREAD

**Issue by hirro** [Availity/availity-reactstrap-validation#73]
Hi, 

I am trying to validate data on a form where the user must provide information in field A or field B (or both). Once B is valid, I want the error message for A to be cleared also.

Anyone who have any idea on how to do that?

I posted a question on SO (https://stackoverflow.com/questions/49780700/validation-depending-on-two-inputs-using-availity-reactstrap-validation) , maybe it is easier to find and more appropriate place to ask questions there, if so just close the issue.

**Comment by TheSharpieOne** [comment]
Currently, this is not possible. Each field only validates itself and changes only trigger validations on itself. There is not a nice workaround to get this to work. You'd have to get a ref to the form and when one input changes, trigger validation on the other input via `formRef.validateInput('other-input-name')`. See: https://stackblitz.com/edit/reactstrap-validation-v2-2pdjv3?file=Example.js
In the future, we want more intelligent ways to have fields know about which other fields are "related" or need to be informed of changes to over fields. 
We have already made some baby steps for this in v3 thanks to the "AvStore" which will help store the relationships and more.

**Comment by hirro** [comment]
Thanks for the answer, awesome! I saw the the response on SO which was perfect. Closing this issue then!
