### ISSUE TITLE
Question: Is there a way to hook into the validation events for pre-built validations, like date?

### ISSUE THREAD

**Issue by ahpearce** [Availity/availity-reactstrap-validation#75]
I have a date AvField, whose validation is working well. However, I am setting some custom state on submit, and displaying certain elements in my component based on there being errors from the submission attempt.

However, the AvField's appear to be hooked into some onBlur event, and when values for the fields change, they are validated, and then the feedback message is either shown or hidden based on that. 

Is there anyway for _me_ to hook into those events, so that I can hide my own elements based on the live update results of the form validation? 

I've seen the async example, but I don't want to write my own validation, just hook into the existing AvField date validation and set my state based on its results, similar to how the form feedback is shown or hidden based on the live validation results.

**Comment by TheSharpieOne** [comment]
You can hook into the onBlur, but you only given the context of the event and not any validation (it's the same as if you used onBlur on an normal input). Validation is async so when the onBlur callback is called the validation may not have finished.
There is no way to hook into the validation. You would have to "duck punch"/"monkey patch" the [`validateOne`](https://github.com/Availity/availity-reactstrap-validation/blob/3e3cd86a37b024b201926bfd714e1e70d062b781/src/AvForm.js#L358) method which you can get via ref to `AvForm`. Doing so would put you right in the middle of validation.
