### ISSUE TITLE
Input Type=number MaxLength

### ISSUE THREAD

**Issue by dkrefta** [Availity/availity-reactstrap-validation#79]
Hello guys,

I trying to block the field after 4  more digits, there is some way to do this with the AvField ?

I did this and show's some error message:
```
maxLength: {
                          value: 4,
                          errorMessage: "Please enter a valid year" 
                        },
```

**Comment by TheSharpieOne** [comment]
You probably want `max="9999"` (or really a reasonable year value) as well as `min="1000"` (or a reasonable year value).
You can still use the validate prop to get the custom error message with those (I'm on mobile so I can't easily type that out)

**Comment by dkrefta** [comment]
No, it was not that, but no problem. 
I already changed the type to 'text' and the maxLength worked :) 

Thanks.

**Comment by YannisMarios** [comment]
Hi,
Here https://availity.github.io/availity-reactstrap-validation/components/validators/, you can see that if maxLength is defined for text input it won't let you exceed 16 characters and so the error message never shows up!
