### ISSUE TITLE
AvField with icon

### ISSUE THREAD

**Issue by aniov** [Availity/availity-reactstrap-validation#80]
Can someone give me an example on how to put an icon in the begining of a <AvField> ?
Thank you.

**Comment by TheSharpieOne** [comment]
`AvField` doesn't allow for that, it's just a simple grouping of components to make the basic use-case of an input with a label and validation message easier.
If you need more advanced markup, such as an inputgroup, you will need to use `AvGroup`, `AvInput`, and `AvFeedback` with reactstrap's InputGroup and it's sub-components (found here: https://reactstrap.github.io/components/input-group/)

Here is an example:
https://stackblitz.com/edit/reactstrap-validation-v2-azxdwp?file=Example.js

```jsx
<AvGroup>
  <Label for="amount">Amount</Label>
  <InputGroup>
    <InputGroupAddon addonType="prepend">
      <InputGroupText>$</InputGroupText>
    </InputGroupAddon>
    <AvInput name="amount" placeholder="0.00" required />
    <AvFeedback>This field is required.</AvFeedback>
  </InputGroup>
</AvGroup>
```
