### ISSUE TITLE
AvField inline field mode

### ISSUE THREAD

**Issue by codeniel17** [Availity/availity-reactstrap-validation#81]
Is it possible to have an inline field? See example below.
![screen shot 2018-05-31 at 10 13 46 am](https://user-images.githubusercontent.com/29366231/40757501-5cb949c8-64bb-11e8-9703-7e66109d64fd.png)
 
At the moment, I've created this with this code:
```
<AvGroup row key={idx}>
   <Label sm={3} for={input.label}>{input.label}</Label>
   <Col sm={9}>
      <AvInput 
            required={input.isRequired}
            id={input.name}
            type={input.type} 
            name={input.name} 
            placeholder={input.label}
            autoComplete={input.name} 
            value={data[input.name]}
       />
      <AvFeedback>This is an error!</AvFeedback>
   </Col>
</AvGroup>
```

So it would be nice if the AvGroup for example will handle the equivalent `validate` prop of the AvField

**Comment by TheSharpieOne** [comment]
There is a `grid` prop on `AvField`, it accepts and object which contains the various breakpoints as the keys and the number of columns the _input_ should use (out of 12) for the value. The label gets the rest of the 12 columns.

https://stackblitz.com/edit/reactstrap-validation-v2-694g4l?file=Example.js

```jsx
        <AvForm onValidSubmit={this.onValidSubmit} onInvalidSubmit={this.onInvalidSubmit}>
          <AvField label="Email Address" name="email" type="email" required grid={{xs: 7}} />
          <AvField label="Confirm Email Address" name="confirmEmail" type="email" required grid={{xs: 7}} />
          <div className="text-right">
            <Button>Submit</Button>
          </div>
        </AvForm>
```

**Comment by sravan464** [comment]
`grid` prop is not working on `AvRadioGroup`
