### ISSUE TITLE
Add 'datetime-local' to htmlValidationTypes

### ISSUE THREAD

**Issue by mattrei** [Availity/availity-reactstrap-validation#82]
Hi, 

according to the MDN the [datetime](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime) input type is depreacted. Its successor is the [datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) however this does not work with this library because it is not stated as a [validation type](https://github.com/Availity/availity-reactstrap-validation/blob/3e3cd86a37b024b201926bfd714e1e70d062b781/src/AvBaseInput.js#L17)

This would be an easy fix.
Best

**Comment by GoPro16** [comment]
The `datetime-local` is not available in all browsers according to the mozilla docs so we probably won't update to have this validation type as the default. However, if you are still wanting it feel free to send a PR.
