### ISSUE TITLE
Date Range properties not working for Availity react date picker

### ISSUE THREAD

**Issue by AlpeshMN** [Availity/availity-reactstrap-validation#83]
Hi @TheSharpieOne, Hope you can help me here for Date picker issue. We are using **Availity react date picker** for my project where I want to **restrict future dates**. As well as we want to disable/restrict dates which are older than **7 years of time exactly from today's date**. What are the prop to use here? (For start and end two separate date picker, future dates should be disable for both and user should not be allowed to select start date older than 7 years of time exactly from today's date.

**Comment by TheSharpieOne** [comment]
There are a few ways to do this
- Use `min`/`max` props with the ISO format (`yyyy-mm-dd`) for the dates you want. This will no only add validation restricting the date to that range, but also let the browser restrict the built-in date picker / calendar to that range as well.
- Use `validate` prop with `dateRange` key indicating a `start` and `end` object with the restrictions you need (for your case above, it would be `validate={{ dateRange: { start: { value: -7, units: 'years', }, end: { value: 0, units: 'days', } } }}`. This will generate a better error message out-of-the-box, but does not restrict the built in date picker / calendar to that range.
- Use both. You get a better error message as well as letting the browser restrict the built-in date picker / calendar to that range.

Check out this example: https://stackblitz.com/edit/reactstrap-validation-v2-zes3nw?file=Example.js

```jsx
import React, { Component } from 'react';
import { Button, Label, FormGroup } from 'reactstrap';
import { AvForm, AvField, AvGroup, AvInput, AvRadioGroup, AvRadio, AvFeedback } from 'availity-reactstrap-validation';

// explicitly generate the start and end dates.
const now = new Date().toJSON().split('T')[0];
let sevenYearsAgo = new Date();
sevenYearsAgo.setFullYear(sevenYearsAgo.getFullYear() - 7);
sevenYearsAgo = sevenYearsAgo.toJSON().split('T')[0];

class Example extends Component {
  state = {};
  onValidSubmit = (event, values) => {
    this.setState({ values });
  };
  onInvalidSubmit = (event, errors, values) => {
    this.setState({ errors, values });
  };
  render() {
    const { errors, values } = this.state;
    return (
      <div>
        <AvForm onValidSubmit={this.onValidSubmit} onInvalidSubmit={this.onInvalidSubmit}>
          <AvField name="dateminmax" label="min/max" type="date" min={sevenYearsAgo} max={now} helpMessage="This is a more native approch. The browser will limit the built in calendar/date picker to the min/max range, but you have to set the dates explicitly and not relativly." />

          <AvField name="datevalidaterange" label="Validate Range" type="date" validate={{ dateRange: { start: { value: -7, units: 'years', }, end: { value: 0, units: 'days', } } }} helpMessage="This allows for easier relative date validations and gives a better error message, but it does not limit the built in calendar/date picker to the min/max range." />


          <AvField name="datecombovalidation" label="Validate Range" type="date" validate={{ dateRange: { start: { value: -7, units: 'years', }, end: { value: 0, units: 'days', } } }} min={sevenYearsAgo} max={now} helpMessage="Combines both to give the best experience." />
          <Button>Submit</Button>
        </AvForm>
        <br />
        {errors && errors.length && <pre>Errors: {JSON.stringify(errors, null, 2)}</pre>}
        {values && <pre>Values: {JSON.stringify(values, null, 2)}</pre>}
      </div>
    )
  }
}

export default Example;
```

**Comment by AlpeshMN** [comment]
Thanks @TheSharpieOne, for your quick reply. It's working very well now for me. :)

**Comment by manojkarri6** [comment]
@AlpeshMN @TheSharpieOne 

But there is an issue with the availity-reactstrap-validation date field. 

**Steps to Re-produce the issue:**

1. First enter the correct date 
2. Then remove either mm or dd or yyyy
3. Now we will see the validation error message - "This field is invalid".
4. And now try to select the date using date picker.
5. we still see the validation error message after the entering/selecting the correct date using the date picker.

https://stackblitz.com/edit/reactstrap-validation-v2-zes3nw?file=Example.js

![image](https://user-images.githubusercontent.com/101058458/176391996-07d2cd01-8d8d-4f3f-bfaf-95253a8a4ed9.png)


Is there any work around inorder to fix this issue?
