### ISSUE TITLE
Dynamically added field values are not getting

### ISSUE THREAD

**Issue by jithesh-bridge** [Availity/availity-reactstrap-validation#84]
I have a section in my form which is dynamically generated like below:

`<AvInput required name={'row_quantity_'+idx} id={'row_quantity_'+idx}/>`

but in my form submit, inside values I am not getting these fields properly. In fact they don't even capture the name properly. This is the form `values` dump:

![untitled](https://user-images.githubusercontent.com/40022896/41720977-41bd2bda-7582-11e8-8ca6-9a7c09da1bd4.png)

**Comment by TheSharpieOne** [comment]
Checkout this: https://stackblitz.com/edit/reactstrap-validation-v2-yj83zh?file=Example.js

![dynamic-inputs](https://user-images.githubusercontent.com/664714/41744566-211a60c4-7572-11e8-9f60-8000bad0e63e.gif)

```jsx
import React, { Component } from 'react';
import { Button, Label, FormGroup } from 'reactstrap';
import { AvForm, AvField, AvGroup, AvInput, AvRadioGroup, AvRadio, AvFeedback } from 'availity-reactstrap-validation';

class Example extends Component {
  state = {inputs: []};
  addInput = () => {
    this.setState(({inputs}) => ({inputs: inputs.concat(['a'])}));
  }
  onValidSubmit = (event, values) => {
    this.setState({values});
  };
  onInvalidSubmit = (event, errors, values) => {
    this.setState({errors, values});
  };
  render() {
    const { errors, values } = this.state;
    return (
      <div>
        <AvForm onValidSubmit={this.onValidSubmit} onInvalidSubmit={this.onInvalidSubmit}>
          {this.state.inputs.map((input, idx) => <AvInput required name={'row_quantity_'+idx} />)}
          <Button color="info" onClick={this.addInput}>Add dynamic input</Button>{' '}
          <Button color="primary">Submit</Button>
        </AvForm>
        <br />
        {errors && errors.length && <pre>Errors: {JSON.stringify(errors, null, 2)}</pre>}
        {values && <pre>Values: {JSON.stringify(values, null, 2)}</pre>}
      </div>
    )
  }
}

export default Example;
```

**Comment by Abdull** [comment]
How about dynamically removing inputs?

I made a stackblitz at https://stackblitz.com/edit/reactstrap-validation-v2-ynsdku?file=Example.js .
Clicking the *Remove first dynamic input* will remove the first element in the `inputs` state array.

Yet the `AvInput` components will behave as if the last element was removed.

**Comment by TheSharpieOne** [comment]
This because you are not really removing the first input, you are removing the last input. Inputs are identified by their `name`, since you are using the index (`idx`), when you remove the first input, you are still rendering `row_quantity_0` and `row_quantity_1`, and have only removed `row_quantity_2` (the last one).

Using index for key (which you were also missing) is generally a bad thing, an similar bad for `name` which is used as a "key" for the fields.

Here is a sample where index is not used, instead each input is given an id/key which doesn't change per input when an input is added or removed:
https://stackblitz.com/edit/reactstrap-validation-v2-4zra92?file=Example.js

**Comment by jayalakshmi-rm** [comment]
@Abdull & @jithesh-bridge In **your code key is not updated in the loop**. Kindly check example given by @TheSharpieOne In the Key has used properly.

`{this.state.inputs.map((input) => <AvInput **key={input}** required name={'row_quantity_'+input} />)}`

https://stackblitz.com/edit/reactstrap-validation-v2-4zra92?file=Example.js
