### ISSUE TITLE
Integrate react-select within AvForm?

### ISSUE THREAD

**Issue by bonniss** [Availity/availity-reactstrap-validation#90]
Hi guys, I'm using an AvForm, which originally contained only Av components. It works fine. Now i'm trying to replace the "select" input in the form by a customized react-select component like this: 
```
import React from 'react';
import Select from 'react-select';
export default class RSelect extends React.Component<ISelectProps> {
    state = {
        selectedOption: null,
    }
    handleChange = (selectedOption) => {
        this.setState({ selectedOption });
    }
    render() {
        const { selectedOption } = this.state;
        return (
            <div>
                <Select
                    value={selectedOption}
                    onChange={this.handleChange}
                    options={this.props.options}
                    isSearchable={this.props.isSearchable}
                    name={this.props.name}
                    className={this.props.className}
                    placeholder={this.props.placeholder}
                />                
            </div>
        );
    }
}
```
When i inspect the underlying DOM element, this one actually generates a HTML hidden input:
`<input type="hidden" name="this.props.name" value="selectedOption">`
, in order to be recognized by the form. But it failed. I've test by using an AvField with same name and value, it works. So is there a general method to make not only react-select, but others modules if needed, be able to be compatible with AvForm?

**Comment by TheSharpieOne** [comment]
There is this thing: [`@availity/reactstrap-validation-select`](https://www.npmjs.com/package/@availity/reactstrap-validation-select) which might be a little overkill, but it integrates react-select with availity-reactstrap-validation. The package itself doesn't provide a pre-compiled version (you'd be required to enable transpilation of the package in your build): https://github.com/Availity/availity-react/blob/master/packages/reactstrap-validation-select/AvSelect.js
You can use that as an example or starting point if you want.

The problem is that react-select doesn't act like a native input. It doesn't sent events for changes and has more/different change events (input change vs select change).

**Comment by bonniss** [comment]
Thank @TheSharpieOne , you suggested me some thoughts and it works now;

**Comment by AbderrahimRayes** [comment]
Hi @TheSharpieOne , I'm new to react and Webpack ... , How can I make webpack transpile the package , I always get an error :

`Module parse failed: Unexpected token (10:19)
You may need an appropriate loader to handle this file type.
| 
| class AvResourceSelect extends Component {
>   static propTypes = {
|     requestConfig: PropTypes.object,
|     resource: PropTypes.shape({

 @ ./node_modules/@availity/reactstrap-validation-select/index.js 3:0-50 6:0-43
 @ multi react-hot-loader/patch ./node_modules/@availity/reactstrap-validation-select ./src/main/webapp/app/index

 error  in ./node_modules/@availity/reactstrap-validation-select/AvSelect.js
`

I'm using webpack with npm, this is what is in my webpack.dev.json file : 



`const webpack = require('webpack');
const writeFilePlugin = require('write-file-webpack-plugin');
const webpackMerge = require('webpack-merge');
const BrowserSyncPlugin = require('browser-sync-webpack-plugin');
const FriendlyErrorsWebpackPlugin = require('friendly-errors-webpack-plugin');
const SimpleProgressWebpackPlugin = require('simple-progress-webpack-plugin');
const WebpackNotifierPlugin = require('webpack-notifier');
const path = require('path');

const utils = require('./utils.js');
const commonConfig = require('./webpack.common.js');

const ENV = 'development';

module.exports = (options) => webpackMerge(commonConfig({env: ENV}), {
  devtool: 'cheap-module-source-map', // https://reactjs.org/docs/cross-origin-errors.html
  mode: ENV,
  entry: [
    'react-hot-loader/patch',
    './src/main/webapp/app/index'
  ],
  output: {
    path: utils.root('target/www'),
    filename: 'app/[name].bundle.js',
    chunkFilename: 'app/[id].chunk.js'
  },
  module: {
    rules: [
      {
        test: /\.(sa|sc|c)ss$/,
        loaders: ['style-loader', 'css-loader', 'postcss-loader', 'sass-loader']
      },
      {
        test: /\.js$/, // Transform all .js files required somewhere with Babel
        exclude: [/node_modules/],
        include: [/node_modules[\\/](?!@av).*/],
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['babel-preset-env']
          }
        },
      },
    ]
  },
  devServer: {
    stats: options.stats,
    hot: true,
    contentBase: './target/www',
    proxy: [{
      context: [
        /* jhipster-needle-add-entity-to-webpack - JHipster will add entity api paths here */
        '/api',
        '/management',
        '/swagger-resources',
        '/v2/api-docs',
        '/h2-console',
        '/auth'
      ],
      target: 'http://127.0.0.1:8080',
      secure: false,
      headers: {host: 'localhost:9000'}
    }, {
      context: [
        '/websocket'
      ],
      target: 'ws://127.0.0.1:8080',
      ws: true
    }],
    watchOptions: {
      ignored: /node_modules/
    }
  },
  plugins: [
    new SimpleProgressWebpackPlugin({
      format: options.stats === 'minimal' ? 'compact' : 'expanded'
    }),
    new FriendlyErrorsWebpackPlugin(),
    new BrowserSyncPlugin({
      host: 'localhost',
      port: 9000,
      proxy: {
        target: 'http://localhost:9060',
        ws: true
      }
    }, {
      reload: false
    }),
    new webpack.HotModuleReplacementPlugin(),
    new writeFilePlugin(),
    new webpack.WatchIgnorePlugin([
      utils.root('src/test'),
    ]),
    new WebpackNotifierPlugin({
      title: 'JHipster',
      contentImage: path.join(__dirname, 'logo-jhipster.png')
    })
  ]
});
`

As you can see i added the babel loader but it still not working,  any help please :)

**Comment by TheSharpieOne** [comment]
@AbderrahimRayes can you try removing the `exclude` and set the `include` to `['.', /node_modules[\\/](?=@av).*/]`
