### ISSUE TITLE
Using mask or another custom Component

### ISSUE THREAD

**Issue by cavarzan** [Availity/availity-reactstrap-validation#91]
I'm trying to use a custom component, like a Phone / Mask / Currency Component, but I didn't find any issue or documentation related.

Looking at the source, I try to use the `children` props, without success.

Is this feature supported?

Thanks!

**Comment by TheSharpieOne** [comment]
You can use the `tag` prop to provide a custom component or element.

**Comment by cavarzan** [comment]
Great!
