### ISSUE TITLE
Send AvForm as ref to its child by props?

### ISSUE THREAD

**Issue by bonniss** [Availity/availity-reactstrap-validation#92]
Hi guys;
I'm following the example of @TheSharpieOne 
https://stackblitz.com/edit/reactstrap-validation-v2-2pdjv3?file=Example.js
I try to modify the example to my scenarios. 2 things that make me confused:
1. My current React version is 16.4.2. Upon the React doc:
https://reactjs.org/docs/refs-and-the-dom.html
The ref is stored in an instance's field, and created by React.createRef(). So I change the example to:
https://stackblitz.com/edit/use-react-createref?file=Example.js
It stops working when enter the input;
2. If i want to pass the parent AvForm to an React element by props to take validation on multiple inputs, e.g check if the "min" number is less than the "max" number and vice versa, like:
https://stackblitz.com/edit/pass-ref-to-custom-element?file=myinput.js
It certainly has some errors round there;
I hope the documentation on each element available soon, it will be helpful to make elements to customized easier. Would you give me some advices?

**Comment by TheSharpieOne** [comment]
`React.createRef()` is a newer function, you need to use `react` _and_ `react-dom` 16.3+. react-dom was not using 16.3+ in the stackblitz examples you posted.

1. Just upgrading the deps resulted in it working as expected: https://stackblitz.com/edit/use-react-createref-qp4zlc?file=Example.js

2. Use _can_ pass the ref down, but as a child component of `AvForm` you can more easily get access to the `context` `AvForm` exposes. It is not documented as it is more/less internal methods to how the validation library communicates, but here is what is exposed:
https://github.com/Availity/availity-reactstrap-validation/blob/d5ec2726a6085007e4b99291a88b1ed4fb700303/src/AvForm.js#L122-L142

[`context.AvForm.validate`](https://github.com/Availity/availity-reactstrap-validation/blob/d5ec2726a6085007e4b99291a88b1ed4fb700303/src/AvForm.js#L139) which is the same function as `AvForm.validateInput` is probably the one you would be most interested in.
