### ISSUE TITLE
RadioGroup Labels wrong color

### ISSUE THREAD

**Issue by KaseyPowers** [Availity/availity-reactstrap-validation#96]
It looks like adding [this change](https://github.com/Availity/availity-reactstrap-validation/blob/master/src/AvRadioGroup.js#L203) has caused the radio's in our radioGroup to render green text on invalid.
<img width="461" alt="screen shot 2018-10-08 at 11 00 56 am" src="https://user-images.githubusercontent.com/4523739/46617025-c53b7900-cae9-11e8-890c-979e721f6889.png">

It appears that the 'was-validated' class is setting the label to green overriding the is-invalid styles.
I'm not sure if this is an issue with the change or with the css we are using (availity-uikit).

**Comment by TheSharpieOne** [comment]
fixed in v2.2.3
