### ISSUE TITLE
But where is the success/warning status?

### ISSUE THREAD

**Issue by elsheepo** [Availity/availity-reactstrap-validation#99]
Title says it all, where is the success and warning status markers?

**Comment by TheSharpieOne** [comment]
Do you mean the green checkmark and the red "x"? If so, those have more/less been removed from bootstrap v4 (at least from the [form docs](http://getbootstrap.com/docs/4.1/components/forms/#validation)) so they were not added to this project (at least for `AvField`).

You can use `AvGroup` with `AvInput` and `AvFeedback` to customize the output. You can even take `AvField` and modify it in your project to make `AvFieldMarkers` (or something like that).
